## Configuracion de Instancia
server:
  port: 8082
  fullAddress: ${HOST:http://localhost}:${PORT:${server.port}}
  error:
    include-stacktrace: on_param

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-library

## Configuracion de Spring
spring:
  application:
    name: ms-library

## Configuracion secundaria (custom)
getBook:
  url: http://ms-library-inventory-books/products/%s

##Elasticsearch config
elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  credentials:
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PWD}
logging:
  level:
    tracer: TRACE

